### PR TITLE
Update module to use new and improved through2

### PR DESCRIPTION
**Pull request by nitro404**
Fix unit tests not working on non-unix based systems
Update readme with additional badges
Update git ignore file
Add npm ignore file
Add npm package lock file

### CODE REVIEW

**Comment by nitro404** [comment]
Hi! I find this module to be very useful in some situations but it has not been updated in some time, so I took the liberty of updating it to work with newer modules and did some housekeeping. This module still sees a lot of monthly downloads, so it would be nice to see it updated! Thanks!

**Comment by CodeMan99** [comment]
Why did you decide to not support content streams? This plugin shouldn't really care what already exists in the stream.

(I'm not the maintainer, but I was about to go about replacing gulp-util.)

Edit: Oh, I guess the original did the same thing. It was a bit hard to grok the diff.

**Comment by hoho** [comment]
Sorry for the delay. I really appreciate you'd like to keep this thing alive.
It's just I've had a couple of comments (mostly cosmetical ones) and I couldn't find a moment yet.

**Comment by nitro404** [comment]
Not a problem! Yeah it's definitely great for dynamically generating code on the fly and throwing it into a gulp stream in my experience. Please let me know if you need any adjustments made or anything!

@CodeMan99 Yeah I replaced gulp-util as well! I think I forgot to do that originally, but I revised my commit afterwards.

**Comment by CodeMan99** [comment]
@hoho Do you have any time to review this PR? I have some tasks in my queue that would be eased slightly if we could move this forward.

**Review by hoho — COMMENTED** [review]
Hey, sorry for the delay.
I'm ready to merge it, just a couple of questions:
1. Why is package-lock.json committed to the repo?
2. The code formatting differs from what it was before. And probably can live with it, but let's have it consistent through the repo: quotes as the example — the main file has double quotes, the tests file has single quotes (I would prefer the single ones everywhere).

**Comment by nitro404** [comment]
1. Using npm version patch auto-commits the new npm package lock file. I can remove it if you prefer?
2. Sure, I can adjust that as well, not a problem. I'll do so as soon as you respond.

**Comment by hoho** [comment]
1. Yep, let's remove it.
2. I respond :).

**Comment by nitro404** [comment]
Updated as per your request!

**Pull request merged**
